### ISSUE TITLE
About the visualization in this project.

### ISSUE THREAD

**Issue by FXLYZ** [ethanweber/sitcoms3D#14]
Hi, it is a magic work! I am impressed by the great 3D reconstruction visualization in the web site (https://ethanweber.me/sitcoms3D/). I try to use the trained checkpoint to generate the visualization. But I cannot find the code of visualization. I would appreciate it if you could offer me the complete code of visualization (e.g., temporal reconstruction with novel views).

**Comment by ethanweber** [comment]
Hi @FXLYZ, it's a bit tough to supply this code as it's tightly tied to the human reconstruction and NeRF pipeline, which we encourage others to implement in their own setting. However, you can think about it as both moving the human and also moving the camera, and rendering with pyrender at the correct frames. Our notebook should give a sense for how to render individual frames, and then you want to create these joint paths of the humans and camera moving.
