### ISSUE TITLE
Missing keyframes.txt for --image_list_path

### ISSUE THREAD

**Issue by basilevh** [ethanweber/sitcoms3D#16]
Hi!
In https://github.com/ethanweber/sitcoms3D/blob/master/REGISTER_NEW_IMAGES.md there is:
```
python detect.py --height 720 --width 1280 --n 2048 new_images/h5 new_images/images --image-extension jpg
```
However, this crashes with:
```
    assert image_list_path is not None
AssertionError
```
In `detect.py`, it says `--image_list_path` needs to point to `keyframes.txt or keyframes_reg.txt`.
I can't see this file in the repository or downloaded data however. Do you happen to have any advice on how to proceed?
Thank you in advance!

**Comment by geopavlakos** [comment]
This should be the list of the new images that you want to process, so you can create this based on your new data. It's a txt with all the names of the images that you have in the `new_images/images` folder.
