### ISSUE TITLE
Friends Dataset

### ISSUE THREAD

**Issue by sp77-1** [ethanweber/sitcoms3D#17]
how can i get 5k images for ELP-apartment?
it seems you use more than 5400 images for colmap, but there is only 171 images in data folder. Could you share the full dataset of it?

**Comment by geopavlakos** [comment]
You can find all the images we used for COLMAP [here](https://drive.google.com/file/d/1B3FkRy-BlMBrsoYSkIgOdWRzpnccMQoX/view?usp=drive_link). The zip file includes the images and the sparse reconstruction for all the rooms.
