### ISSUE TITLE
Supplemental materials

### ISSUE THREAD

**Issue by xiyichen** [ethanweber/sitcoms3D#2]
In the paper it is mentioned multiple times to refer to the supplemental materials for more details. Where can I find it?

**Comment by ethanweber** [comment]
Hi @xiyichen, thanks for bringing this to our attention. We've updated the [project page](https://ethanweber.me/sitcoms3D/) with [the link](https://ethanweber.me/sitcoms3D/docs/sitcoms3D-supp.pdf).
