### ISSUE TITLE
Question about SMPL data

### ISSUE THREAD

**Issue by sghong977** [ethanweber/sitcoms3D#6]
Hi, I'm trying your method on the custom dataset, but I have a problem to get human_data and human_pairs.
Did you implement multi-shot human reconstruction by extending SPIN (https://github.com/nkolot/SPIN)?
I wonder if you have a plan to share the code of calibrated multi-shot human reconstruction.

**Comment by ethanweber** [comment]
Hi @sghong977, we don't use SPIN but use [SMPLify](https://arxiv.org/abs/1607.08128). We don't plan to release the code for this at the moment, but creating a tool to scale our method on any videos would be an incredible contribution. Our method is documented in detail in the paper if you want to replicate that portion of the paper. Thank you for the question!
